name: "@inkohx/logger CI"

on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check errors.
        run: npm run compile:test
