name: "Publish @inkohx/logger"

on:
  push:
    branches:
      - stable

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check errors.
        run: npm run compile:test

  publish:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: https://npm.pkg.github.com/
          scope: "InkoHX"
      - name: Install
        run: npm install
      - name: "Publish @inkohx/logger"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: stable
          BRANCH: gh-pages
          FOLDER: docs
          BUILD_SCRIPT: npm install && npm run docs
