name: "Publish @inkohx/logger"

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check errors.
        run: npm run compile:test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: https://npm.pkg.github.com/
          scope: "InkoHX"
      - name: "Publish @inkohx/logger"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
